### PR TITLE
Ex2_Sprint9-JS

### PR DESCRIPTION
**Pull request by DANIEL886886**

### CODE REVIEW

**Review by MarcelBuian — CHANGES_REQUESTED** [review]
Si daca incerci `console.log(getRandomNumber(200, 243))` ?  :) 

 Cred ca iti lipseste inca o operatie la urma

**Comment by DANIEL886886** [comment]
const getRandomNumber = (start, end) => (start < end) && (typeof start === "number") && (typeof end === "number") ? Math.floor(Math.random() * (end - start) + start) : "Invalid input: start must be less than end";
//added protection in the function to verify that typeof start & end is number and that start needs to be < end. 
console.log(getRandomNumber(200, 243))
// output 215 
console.log(getRandomNumber(243, 243))
// output Invalid input: start must be less than end
console.log(getRandomNumber(242, 243))
// output 242

Am testat codul si acum este ok

**Comment by DANIEL886886** [comment]
Am mai aduagat la final in operatie (+start)

**Review by MarcelBuian — APPROVED** [review]
Acum e bine 👍

**Pull request merged**
